<?php

array(7) {
    [0]=> array(70) {
        ["id"]=> int(21522457) ["description"]=> string(0) "" ["name"]=> string(7) "projet7" ["name_with_namespace"]=> string(22) "Loic Le Meut / projet7" ["path"]=> string(7) "projet7" ["path_with_namespace"]=> string(15) "llemeut/projet7" ["created_at"]=> string(24) "2020-10-02T12:38:12.147Z" ["default_branch"]=> string(6) "master" ["tag_list"]=> array(0) {
        } ["ssh_url_to_repo"]=> string(34) "git@gitlab.com:llemeut/projet7.git" ["http_url_to_repo"]=> string(38) "https://gitlab.com/llemeut/projet7.git" ["web_url"]=> string(34) "https://gitlab.com/llemeut/projet7" ["readme_url"]=> string(58) "https://gitlab.com/llemeut/projet7/-/blob/master/README.md" ["avatar_url"]=> NULL ["forks_count"]=> int(0) ["star_count"]=> int(0) ["last_activity_at"]=> string(24) "2020-10-02T12:38:12.147Z" ["namespace"]=> array(8) {
            ["id"]=> int(9415460) ["name"]=> string(12) "Loic Le Meut" ["path"]=> string(7) "llemeut" ["kind"]=> string(4) "user" ["full_path"]=> string(7) "llemeut" ["parent_id"]=> NULL ["avatar_url"]=> string(84) "https://secure.gravatar.com/avatar/60525e27078933b6086f324703846462?s=80&d=identicon" ["web_url"]=> string(26) "https://gitlab.com/llemeut" } ["_links"]=> array(7) {
            ["self"]=> string(43) "https://gitlab.com/api/v4/projects/21522457" ["issues"]=> string(50) "https://gitlab.com/api/v4/projects/21522457/issues" ["merge_requests"]=> string(58) "https://gitlab.com/api/v4/projects/21522457/merge_requests" ["repo_branches"]=> string(63) "https://gitlab.com/api/v4/projects/21522457/repository/branches" ["labels"]=> string(50) "https://gitlab.com/api/v4/projects/21522457/labels" ["events"]=> string(50) "https://gitlab.com/api/v4/projects/21522457/events" ["members"]=> string(51) "https://gitlab.com/api/v4/projects/21522457/members" } ["packages_enabled"]=> bool(true) ["empty_repo"]=> bool(false) ["archived"]=> bool(false) ["visibility"]=> string(7) "private" ["owner"]=> array(6) {
            ["id"]=> int(7126894) ["name"]=> string(12) "Loic Le Meut" ["username"]=> string(7) "llemeut" ["state"]=> string(6) "active" ["avatar_url"]=> string(84) "https://secure.gravatar.com/avatar/60525e27078933b6086f324703846462?s=80&d=identicon" ["web_url"]=> string(26) "https://gitlab.com/llemeut" } ["resolve_outdated_diff_discussions"]=> bool(false) ["container_registry_enabled"]=> bool(true) ["container_expiration_policy"]=> array(7) {
            ["cadence"]=> string(2) "1d" ["enabled"]=> bool(true) ["keep_n"]=> int(10) ["older_than"]=> string(3) "90d" ["name_regex"]=> NULL ["name_regex_keep"]=> NULL ["next_run_at"]=> string(24) "2020-10-03T12:38:12.163Z" } ["issues_enabled"]=> bool(true) ["merge_requests_enabled"]=> bool(true) ["wiki_enabled"]=> bool(true) ["jobs_enabled"]=> bool(true) ["snippets_enabled"]=> bool(true) ["service_desk_enabled"]=> bool(true) ["service_desk_address"]=> string(60) "incoming+llemeut-projet7-21522457-issue-@incoming.gitlab.com" ["can_create_merge_request_in"]=> bool(true) ["issues_access_level"]=> string(7) "enabled" ["repository_access_level"]=> string(7) "enabled" ["merge_requests_access_level"]=> string(7) "enabled" ["forking_access_level"]=> string(7) "enabled" ["wiki_access_level"]=> string(7) "enabled" ["builds_access_level"]=> string(7) "enabled" ["snippets_access_level"]=> string(7) "enabled" ["pages_access_level"]=> string(7) "private" ["emails_disabled"]=> NULL ["shared_runners_enabled"]=> bool(true) ["lfs_enabled"]=> bool(true) ["creator_id"]=> int(7126894) ["import_status"]=> string(4) "none" ["open_issues_count"]=> int(0) ["ci_default_git_depth"]=> int(50) ["public_jobs"]=> bool(true) ["build_timeout"]=> int(3600) ["auto_cancel_pending_pipelines"]=> string(7) "enabled" ["build_coverage_regex"]=> NULL ["ci_config_path"]=> string(0) "" ["shared_with_groups"]=> array(1) {
            [0]=> array(5) {
                ["group_id"]=> int(9661888) ["group_name"]=> string(7) "itescia" ["group_full_path"]=> string(7) "itescia" ["group_access_level"]=> int(40) ["expires_at"]=> NULL } } ["only_allow_merge_if_pipeline_succeeds"]=> bool(false) ["allow_merge_on_skipped_pipeline"]=> NULL ["request_access_enabled"]=> bool(true) ["only_allow_merge_if_all_discussions_are_resolved"]=> bool(false) ["remove_source_branch_after_merge"]=> bool(true) ["printing_merge_request_link_enabled"]=> bool(true) ["merge_method"]=> string(5) "merge" ["suggestion_commit_message"]=> NULL ["auto_devops_enabled"]=> bool(false) ["auto_devops_deploy_strategy"]=> string(10) "continuous" ["autoclose_referenced_issues"]=> bool(true) ["external_authorization_classification_label"]=> string(0) "" ["compliance_frameworks"]=> array(0) {
        } ["permissions"]=> array(2) {
            ["project_access"]=> array(2) {
                ["access_level"]=> int(40) ["notification_level"]=> int(3) } ["group_access"]=> NULL } } [1]=> array(70) {
        ["id"]=> int(21256897) ["description"]=> string(0) "" ["name"]=> string(7) "projet6" ["name_with_namespace"]=> string(22) "Loic Le Meut / projet6" ["path"]=> string(7) "projet6" ["path_with_namespace"]=> string(15) "llemeut/projet6" ["created_at"]=> string(24) "2020-09-21T07:24:11.271Z" ["default_branch"]=> string(6) "master" ["tag_list"]=> array(0) {
        } ["ssh_url_to_repo"]=> string(34) "git@gitlab.com:llemeut/projet6.git" ["http_url_to_repo"]=> string(38) "https://gitlab.com/llemeut/projet6.git" ["web_url"]=> string(34) "https://gitlab.com/llemeut/projet6" ["readme_url"]=> string(58) "https://gitlab.com/llemeut/projet6/-/blob/master/README.md" ["avatar_url"]=> NULL ["forks_count"]=> int(0) ["star_count"]=> int(0) ["last_activity_at"]=> string(24) "2020-09-30T13:07:11.645Z" ["namespace"]=> array(8) {
            ["id"]=> int(9415460) ["name"]=> string(12) "Loic Le Meut" ["path"]=> string(7) "llemeut" ["kind"]=> string(4) "user" ["full_path"]=> string(7) "llemeut" ["parent_id"]=> NULL ["avatar_url"]=> string(84) "https://secure.gravatar.com/avatar/60525e27078933b6086f324703846462?s=80&d=identicon" ["web_url"]=> string(26) "https://gitlab.com/llemeut" } ["_links"]=> array(7) {
            ["self"]=> string(43) "https://gitlab.com/api/v4/projects/21256897" ["issues"]=> string(50) "https://gitlab.com/api/v4/projects/21256897/issues" ["merge_requests"]=> string(58) "https://gitlab.com/api/v4/projects/21256897/merge_requests" ["repo_branches"]=> string(63) "https://gitlab.com/api/v4/projects/21256897/repository/branches" ["labels"]=> string(50) "https://gitlab.com/api/v4/projects/21256897/labels" ["events"]=> string(50) "https://gitlab.com/api/v4/projects/21256897/events" ["members"]=> string(51) "https://gitlab.com/api/v4/projects/21256897/members" } ["packages_enabled"]=> bool(true) ["empty_repo"]=> bool(false) ["archived"]=> bool(false) ["visibility"]=> string(7) "private" ["owner"]=> array(6) {
            ["id"]=> int(7126894) ["name"]=> string(12) "Loic Le Meut" ["username"]=> string(7) "llemeut" ["state"]=> string(6) "active" ["avatar_url"]=> string(84) "https://secure.gravatar.com/avatar/60525e27078933b6086f324703846462?s=80&d=identicon" ["web_url"]=> string(26) "https://gitlab.com/llemeut" } ["resolve_outdated_diff_discussions"]=> bool(false) ["container_registry_enabled"]=> bool(true) ["container_expiration_policy"]=> array(7) {
            ["cadence"]=> string(2) "1d" ["enabled"]=> bool(true) ["keep_n"]=> int(10) ["older_than"]=> string(3) "90d" ["name_regex"]=> NULL ["name_regex_keep"]=> NULL ["next_run_at"]=> string(24) "2020-09-29T07:15:03.781Z" } ["issues_enabled"]=> bool(true) ["merge_requests_enabled"]=> bool(true) ["wiki_enabled"]=> bool(true) ["jobs_enabled"]=> bool(true) ["snippets_enabled"]=> bool(true) ["service_desk_enabled"]=> bool(true) ["service_desk_address"]=> string(60) "incoming+llemeut-projet6-21256897-issue-@incoming.gitlab.com" ["can_create_merge_request_in"]=> bool(true) ["issues_access_level"]=> string(7) "enabled" ["repository_access_level"]=> string(7) "enabled" ["merge_requests_access_level"]=> string(7) "enabled" ["forking_access_level"]=> string(7) "enabled" ["wiki_access_level"]=> string(7) "enabled" ["builds_access_level"]=> string(7) "enabled" ["snippets_access_level"]=> string(7) "enabled" ["pages_access_level"]=> string(7) "private" ["emails_disabled"]=> NULL ["shared_runners_enabled"]=> bool(true) ["lfs_enabled"]=> bool(true) ["creator_id"]=> int(7126894) ["import_status"]=> string(4) "none" ["open_issues_count"]=> int(0) ["ci_default_git_depth"]=> int(50) ["public_jobs"]=> bool(true) ["build_timeout"]=> int(3600) ["auto_cancel_pending_pipelines"]=> string(7) "enabled" ["build_coverage_regex"]=> NULL ["ci_config_path"]=> string(0) "" ["shared_with_groups"]=> array(1) {
            [0]=> array(5) {
                ["group_id"]=> int(9661888) ["group_name"]=> string(7) "itescia" ["group_full_path"]=> string(7) "itescia" ["group_access_level"]=> int(40) ["expires_at"]=> NULL } } ["only_allow_merge_if_pipeline_succeeds"]=> bool(false) ["allow_merge_on_skipped_pipeline"]=> NULL ["request_access_enabled"]=> bool(true) ["only_allow_merge_if_all_discussions_are_resolved"]=> bool(false) ["remove_source_branch_after_merge"]=> bool(true) ["printing_merge_request_link_enabled"]=> bool(true) ["merge_method"]=> string(5) "merge" ["suggestion_commit_message"]=> NULL ["auto_devops_enabled"]=> bool(false) ["auto_devops_deploy_strategy"]=> string(10) "continuous" ["autoclose_referenced_issues"]=> bool(true) ["external_authorization_classification_label"]=> string(0) "" ["compliance_frameworks"]=> array(0) {
        } ["permissions"]=> array(2) {
            ["project_access"]=> array(2) {
                ["access_level"]=> int(40) ["notification_level"]=> int(3) } ["group_access"]=> NULL } } [2]=> array(70) {
        ["id"]=> int(21256865) ["description"]=> string(0) "" ["name"]=> string(7) "projet5" ["name_with_namespace"]=> string(22) "Loic Le Meut / projet5" ["path"]=> string(7) "projet5" ["path_with_namespace"]=> string(15) "llemeut/projet5" ["created_at"]=> string(24) "2020-09-21T07:22:42.606Z" ["default_branch"]=> string(6) "master" ["tag_list"]=> array(0) {
        } ["ssh_url_to_repo"]=> string(34) "git@gitlab.com:llemeut/projet5.git" ["http_url_to_repo"]=> string(38) "https://gitlab.com/llemeut/projet5.git" ["web_url"]=> string(34) "https://gitlab.com/llemeut/projet5" ["readme_url"]=> string(58) "https://gitlab.com/llemeut/projet5/-/blob/master/README.md" ["avatar_url"]=> NULL ["forks_count"]=> int(0) ["star_count"]=> int(0) ["last_activity_at"]=> string(24) "2020-10-07T07:57:31.541Z" ["namespace"]=> array(8) {
            ["id"]=> int(9415460) ["name"]=> string(12) "Loic Le Meut" ["path"]=> string(7) "llemeut" ["kind"]=> string(4) "user" ["full_path"]=> string(7) "llemeut" ["parent_id"]=> NULL ["avatar_url"]=> string(84) "https://secure.gravatar.com/avatar/60525e27078933b6086f324703846462?s=80&d=identicon" ["web_url"]=> string(26) "https://gitlab.com/llemeut" } ["_links"]=> array(7) {
            ["self"]=> string(43) "https://gitlab.com/api/v4/projects/21256865" ["issues"]=> string(50) "https://gitlab.com/api/v4/projects/21256865/issues" ["merge_requests"]=> string(58) "https://gitlab.com/api/v4/projects/21256865/merge_requests" ["repo_branches"]=> string(63) "https://gitlab.com/api/v4/projects/21256865/repository/branches" ["labels"]=> string(50) "https://gitlab.com/api/v4/projects/21256865/labels" ["events"]=> string(50) "https://gitlab.com/api/v4/projects/21256865/events" ["members"]=> string(51) "https://gitlab.com/api/v4/projects/21256865/members" } ["packages_enabled"]=> bool(true) ["empty_repo"]=> bool(false) ["archived"]=> bool(false) ["visibility"]=> string(7) "private" ["owner"]=> array(6) {
            ["id"]=> int(7126894) ["name"]=> string(12) "Loic Le Meut" ["username"]=> string(7) "llemeut" ["state"]=> string(6) "active" ["avatar_url"]=> string(84) "https://secure.gravatar.com/avatar/60525e27078933b6086f324703846462?s=80&d=identicon" ["web_url"]=> string(26) "https://gitlab.com/llemeut" } ["resolve_outdated_diff_discussions"]=> bool(false) ["container_registry_enabled"]=> bool(true) ["container_expiration_policy"]=> array(7) {
            ["cadence"]=> string(2) "1d" ["enabled"]=> bool(true) ["keep_n"]=> int(10) ["older_than"]=> string(3) "90d" ["name_regex"]=> NULL ["name_regex_keep"]=> NULL ["next_run_at"]=> string(24) "2020-09-29T07:15:03.279Z" } ["issues_enabled"]=> bool(true) ["merge_requests_enabled"]=> bool(true) ["wiki_enabled"]=> bool(true) ["jobs_enabled"]=> bool(true) ["snippets_enabled"]=> bool(true) ["service_desk_enabled"]=> bool(true) ["service_desk_address"]=> string(60) "incoming+llemeut-projet5-21256865-issue-@incoming.gitlab.com" ["can_create_merge_request_in"]=> bool(true) ["issues_access_level"]=> string(7) "enabled" ["repository_access_level"]=> string(7) "enabled" ["merge_requests_access_level"]=> string(7) "enabled" ["forking_access_level"]=> string(7) "enabled" ["wiki_access_level"]=> string(7) "enabled" ["builds_access_level"]=> string(7) "enabled" ["snippets_access_level"]=> string(7) "enabled" ["pages_access_level"]=> string(7) "private" ["emails_disabled"]=> NULL ["shared_runners_enabled"]=> bool(true) ["lfs_enabled"]=> bool(true) ["creator_id"]=> int(7126894) ["import_status"]=> string(4) "none" ["open_issues_count"]=> int(0) ["ci_default_git_depth"]=> int(50) ["public_jobs"]=> bool(true) ["build_timeout"]=> int(3600) ["auto_cancel_pending_pipelines"]=> string(7) "enabled" ["build_coverage_regex"]=> NULL ["ci_config_path"]=> string(0) "" ["shared_with_groups"]=> array(1) {
            [0]=> array(5) {
                ["group_id"]=> int(9661888) ["group_name"]=> string(7) "itescia" ["group_full_path"]=> string(7) "itescia" ["group_access_level"]=> int(40) ["expires_at"]=> NULL } } ["only_allow_merge_if_pipeline_succeeds"]=> bool(false) ["allow_merge_on_skipped_pipeline"]=> NULL ["request_access_enabled"]=> bool(true) ["only_allow_merge_if_all_discussions_are_resolved"]=> bool(false) ["remove_source_branch_after_merge"]=> bool(true) ["printing_merge_request_link_enabled"]=> bool(true) ["merge_method"]=> string(5) "merge" ["suggestion_commit_message"]=> NULL ["auto_devops_enabled"]=> bool(false) ["auto_devops_deploy_strategy"]=> string(10) "continuous" ["autoclose_referenced_issues"]=> bool(true) ["external_authorization_classification_label"]=> string(0) "" ["compliance_frameworks"]=> array(0) {
        } ["permissions"]=> array(2) {
            ["project_access"]=> array(2) {
                ["access_level"]=> int(40) ["notification_level"]=> int(3) } ["group_access"]=> NULL } } [3]=> array(70) {
        ["id"]=> int(21256859) ["description"]=> string(0) "" ["name"]=> string(7) "projet4" ["name_with_namespace"]=> string(22) "Loic Le Meut / projet4" ["path"]=> string(7) "projet4" ["path_with_namespace"]=> string(15) "llemeut/projet4" ["created_at"]=> string(24) "2020-09-21T07:22:21.584Z" ["default_branch"]=> string(6) "master" ["tag_list"]=> array(0) {
        } ["ssh_url_to_repo"]=> string(34) "git@gitlab.com:llemeut/projet4.git" ["http_url_to_repo"]=> string(38) "https://gitlab.com/llemeut/projet4.git" ["web_url"]=> string(34) "https://gitlab.com/llemeut/projet4" ["readme_url"]=> string(58) "https://gitlab.com/llemeut/projet4/-/blob/master/README.md" ["avatar_url"]=> NULL ["forks_count"]=> int(0) ["star_count"]=> int(0) ["last_activity_at"]=> string(24) "2020-09-30T12:53:23.785Z" ["namespace"]=> array(8) {
            ["id"]=> int(9415460) ["name"]=> string(12) "Loic Le Meut" ["path"]=> string(7) "llemeut" ["kind"]=> string(4) "user" ["full_path"]=> string(7) "llemeut" ["parent_id"]=> NULL ["avatar_url"]=> string(84) "https://secure.gravatar.com/avatar/60525e27078933b6086f324703846462?s=80&d=identicon" ["web_url"]=> string(26) "https://gitlab.com/llemeut" } ["_links"]=> array(7) {
            ["self"]=> string(43) "https://gitlab.com/api/v4/projects/21256859" ["issues"]=> string(50) "https://gitlab.com/api/v4/projects/21256859/issues" ["merge_requests"]=> string(58) "https://gitlab.com/api/v4/projects/21256859/merge_requests" ["repo_branches"]=> string(63) "https://gitlab.com/api/v4/projects/21256859/repository/branches" ["labels"]=> string(50) "https://gitlab.com/api/v4/projects/21256859/labels" ["events"]=> string(50) "https://gitlab.com/api/v4/projects/21256859/events" ["members"]=> string(51) "https://gitlab.com/api/v4/projects/21256859/members" } ["packages_enabled"]=> bool(true) ["empty_repo"]=> bool(false) ["archived"]=> bool(false) ["visibility"]=> string(7) "private" ["owner"]=> array(6) {
            ["id"]=> int(7126894) ["name"]=> string(12) "Loic Le Meut" ["username"]=> string(7) "llemeut" ["state"]=> string(6) "active" ["avatar_url"]=> string(84) "https://secure.gravatar.com/avatar/60525e27078933b6086f324703846462?s=80&d=identicon" ["web_url"]=> string(26) "https://gitlab.com/llemeut" } ["resolve_outdated_diff_discussions"]=> bool(false) ["container_registry_enabled"]=> bool(true) ["container_expiration_policy"]=> array(7) {
            ["cadence"]=> string(2) "1d" ["enabled"]=> bool(true) ["keep_n"]=> int(10) ["older_than"]=> string(3) "90d" ["name_regex"]=> NULL ["name_regex_keep"]=> NULL ["next_run_at"]=> string(24) "2020-09-29T07:15:03.164Z" } ["issues_enabled"]=> bool(true) ["merge_requests_enabled"]=> bool(true) ["wiki_enabled"]=> bool(true) ["jobs_enabled"]=> bool(true) ["snippets_enabled"]=> bool(true) ["service_desk_enabled"]=> bool(true) ["service_desk_address"]=> string(60) "incoming+llemeut-projet4-21256859-issue-@incoming.gitlab.com" ["can_create_merge_request_in"]=> bool(true) ["issues_access_level"]=> string(7) "enabled" ["repository_access_level"]=> string(7) "enabled" ["merge_requests_access_level"]=> string(7) "enabled" ["forking_access_level"]=> string(7) "enabled" ["wiki_access_level"]=> string(7) "enabled" ["builds_access_level"]=> string(7) "enabled" ["snippets_access_level"]=> string(7) "enabled" ["pages_access_level"]=> string(7) "private" ["emails_disabled"]=> NULL ["shared_runners_enabled"]=> bool(true) ["lfs_enabled"]=> bool(true) ["creator_id"]=> int(7126894) ["import_status"]=> string(4) "none" ["open_issues_count"]=> int(0) ["ci_default_git_depth"]=> int(50) ["public_jobs"]=> bool(true) ["build_timeout"]=> int(3600) ["auto_cancel_pending_pipelines"]=> string(7) "enabled" ["build_coverage_regex"]=> NULL ["ci_config_path"]=> string(0) "" ["shared_with_groups"]=> array(1) {
            [0]=> array(5) {
                ["group_id"]=> int(9661888) ["group_name"]=> string(7) "itescia" ["group_full_path"]=> string(7) "itescia" ["group_access_level"]=> int(40) ["expires_at"]=> NULL } } ["only_allow_merge_if_pipeline_succeeds"]=> bool(false) ["allow_merge_on_skipped_pipeline"]=> NULL ["request_access_enabled"]=> bool(true) ["only_allow_merge_if_all_discussions_are_resolved"]=> bool(false) ["remove_source_branch_after_merge"]=> bool(true) ["printing_merge_request_link_enabled"]=> bool(true) ["merge_method"]=> string(5) "merge" ["suggestion_commit_message"]=> NULL ["auto_devops_enabled"]=> bool(false) ["auto_devops_deploy_strategy"]=> string(10) "continuous" ["autoclose_referenced_issues"]=> bool(true) ["external_authorization_classification_label"]=> string(0) "" ["compliance_frameworks"]=> array(0) {
        } ["permissions"]=> array(2) {
            ["project_access"]=> array(2) {
                ["access_level"]=> int(40) ["notification_level"]=> int(3) } ["group_access"]=> NULL } } [4]=> array(70) {
        ["id"]=> int(21256854) ["description"]=> string(0) "" ["name"]=> string(7) "projet3" ["name_with_namespace"]=> string(22) "Loic Le Meut / projet3" ["path"]=> string(7) "projet3" ["path_with_namespace"]=> string(15) "llemeut/projet3" ["created_at"]=> string(24) "2020-09-21T07:22:03.077Z" ["default_branch"]=> string(6) "master" ["tag_list"]=> array(0) {
        } ["ssh_url_to_repo"]=> string(34) "git@gitlab.com:llemeut/projet3.git" ["http_url_to_repo"]=> string(38) "https://gitlab.com/llemeut/projet3.git" ["web_url"]=> string(34) "https://gitlab.com/llemeut/projet3" ["readme_url"]=> string(58) "https://gitlab.com/llemeut/projet3/-/blob/master/README.md" ["avatar_url"]=> NULL ["forks_count"]=> int(0) ["star_count"]=> int(0) ["last_activity_at"]=> string(24) "2020-09-30T08:28:39.359Z" ["namespace"]=> array(8) {
            ["id"]=> int(9415460) ["name"]=> string(12) "Loic Le Meut" ["path"]=> string(7) "llemeut" ["kind"]=> string(4) "user" ["full_path"]=> string(7) "llemeut" ["parent_id"]=> NULL ["avatar_url"]=> string(84) "https://secure.gravatar.com/avatar/60525e27078933b6086f324703846462?s=80&d=identicon" ["web_url"]=> string(26) "https://gitlab.com/llemeut" } ["_links"]=> array(7) {
            ["self"]=> string(43) "https://gitlab.com/api/v4/projects/21256854" ["issues"]=> string(50) "https://gitlab.com/api/v4/projects/21256854/issues" ["merge_requests"]=> string(58) "https://gitlab.com/api/v4/projects/21256854/merge_requests" ["repo_branches"]=> string(63) "https://gitlab.com/api/v4/projects/21256854/repository/branches" ["labels"]=> string(50) "https://gitlab.com/api/v4/projects/21256854/labels" ["events"]=> string(50) "https://gitlab.com/api/v4/projects/21256854/events" ["members"]=> string(51) "https://gitlab.com/api/v4/projects/21256854/members" } ["packages_enabled"]=> bool(true) ["empty_repo"]=> bool(false) ["archived"]=> bool(false) ["visibility"]=> string(7) "private" ["owner"]=> array(6) {
            ["id"]=> int(7126894) ["name"]=> string(12) "Loic Le Meut" ["username"]=> string(7) "llemeut" ["state"]=> string(6) "active" ["avatar_url"]=> string(84) "https://secure.gravatar.com/avatar/60525e27078933b6086f324703846462?s=80&d=identicon" ["web_url"]=> string(26) "https://gitlab.com/llemeut" } ["resolve_outdated_diff_discussions"]=> bool(false) ["container_registry_enabled"]=> bool(true) ["container_expiration_policy"]=> array(7) {
            ["cadence"]=> string(2) "1d" ["enabled"]=> bool(true) ["keep_n"]=> int(10) ["older_than"]=> string(3) "90d" ["name_regex"]=> NULL ["name_regex_keep"]=> NULL ["next_run_at"]=> string(24) "2020-09-29T07:15:03.005Z" } ["issues_enabled"]=> bool(true) ["merge_requests_enabled"]=> bool(true) ["wiki_enabled"]=> bool(true) ["jobs_enabled"]=> bool(true) ["snippets_enabled"]=> bool(true) ["service_desk_enabled"]=> bool(true) ["service_desk_address"]=> string(60) "incoming+llemeut-projet3-21256854-issue-@incoming.gitlab.com" ["can_create_merge_request_in"]=> bool(true) ["issues_access_level"]=> string(7) "enabled" ["repository_access_level"]=> string(7) "enabled" ["merge_requests_access_level"]=> string(7) "enabled" ["forking_access_level"]=> string(7) "enabled" ["wiki_access_level"]=> string(7) "enabled" ["builds_access_level"]=> string(7) "enabled" ["snippets_access_level"]=> string(7) "enabled" ["pages_access_level"]=> string(7) "private" ["emails_disabled"]=> NULL ["shared_runners_enabled"]=> bool(true) ["lfs_enabled"]=> bool(true) ["creator_id"]=> int(7126894) ["import_status"]=> string(4) "none" ["open_issues_count"]=> int(0) ["ci_default_git_depth"]=> int(50) ["public_jobs"]=> bool(true) ["build_timeout"]=> int(3600) ["auto_cancel_pending_pipelines"]=> string(7) "enabled" ["build_coverage_regex"]=> NULL ["ci_config_path"]=> string(0) "" ["shared_with_groups"]=> array(1) {
            [0]=> array(5) {
                ["group_id"]=> int(9661888) ["group_name"]=> string(7) "itescia" ["group_full_path"]=> string(7) "itescia" ["group_access_level"]=> int(40) ["expires_at"]=> NULL } } ["only_allow_merge_if_pipeline_succeeds"]=> bool(false) ["allow_merge_on_skipped_pipeline"]=> NULL ["request_access_enabled"]=> bool(true) ["only_allow_merge_if_all_discussions_are_resolved"]=> bool(false) ["remove_source_branch_after_merge"]=> bool(true) ["printing_merge_request_link_enabled"]=> bool(true) ["merge_method"]=> string(5) "merge" ["suggestion_commit_message"]=> NULL ["auto_devops_enabled"]=> bool(false) ["auto_devops_deploy_strategy"]=> string(10) "continuous" ["autoclose_referenced_issues"]=> bool(true) ["external_authorization_classification_label"]=> string(0) "" ["compliance_frameworks"]=> array(0) {
        } ["permissions"]=> array(2) {
            ["project_access"]=> array(2) {
                ["access_level"]=> int(40) ["notification_level"]=> int(3) } ["group_access"]=> NULL } } [5]=> array(70) {
        ["id"]=> int(21256849) ["description"]=> string(0) "" ["name"]=> string(7) "projet2" ["name_with_namespace"]=> string(22) "Loic Le Meut / projet2" ["path"]=> string(7) "projet2" ["path_with_namespace"]=> string(15) "llemeut/projet2" ["created_at"]=> string(24) "2020-09-21T07:21:47.409Z" ["default_branch"]=> string(6) "master" ["tag_list"]=> array(0) {
        } ["ssh_url_to_repo"]=> string(34) "git@gitlab.com:llemeut/projet2.git" ["http_url_to_repo"]=> string(38) "https://gitlab.com/llemeut/projet2.git" ["web_url"]=> string(34) "https://gitlab.com/llemeut/projet2" ["readme_url"]=> string(58) "https://gitlab.com/llemeut/projet2/-/blob/master/README.md" ["avatar_url"]=> NULL ["forks_count"]=> int(0) ["star_count"]=> int(0) ["last_activity_at"]=> string(24) "2020-09-30T08:25:50.183Z" ["namespace"]=> array(8) {
            ["id"]=> int(9415460) ["name"]=> string(12) "Loic Le Meut" ["path"]=> string(7) "llemeut" ["kind"]=> string(4) "user" ["full_path"]=> string(7) "llemeut" ["parent_id"]=> NULL ["avatar_url"]=> string(84) "https://secure.gravatar.com/avatar/60525e27078933b6086f324703846462?s=80&d=identicon" ["web_url"]=> string(26) "https://gitlab.com/llemeut" } ["_links"]=> array(7) {
            ["self"]=> string(43) "https://gitlab.com/api/v4/projects/21256849" ["issues"]=> string(50) "https://gitlab.com/api/v4/projects/21256849/issues" ["merge_requests"]=> string(58) "https://gitlab.com/api/v4/projects/21256849/merge_requests" ["repo_branches"]=> string(63) "https://gitlab.com/api/v4/projects/21256849/repository/branches" ["labels"]=> string(50) "https://gitlab.com/api/v4/projects/21256849/labels" ["events"]=> string(50) "https://gitlab.com/api/v4/projects/21256849/events" ["members"]=> string(51) "https://gitlab.com/api/v4/projects/21256849/members" } ["packages_enabled"]=> bool(true) ["empty_repo"]=> bool(false) ["archived"]=> bool(false) ["visibility"]=> string(7) "private" ["owner"]=> array(6) {
            ["id"]=> int(7126894) ["name"]=> string(12) "Loic Le Meut" ["username"]=> string(7) "llemeut" ["state"]=> string(6) "active" ["avatar_url"]=> string(84) "https://secure.gravatar.com/avatar/60525e27078933b6086f324703846462?s=80&d=identicon" ["web_url"]=> string(26) "https://gitlab.com/llemeut" } ["resolve_outdated_diff_discussions"]=> bool(false) ["container_registry_enabled"]=> bool(true) ["container_expiration_policy"]=> array(7) {
            ["cadence"]=> string(2) "1d" ["enabled"]=> bool(true) ["keep_n"]=> int(10) ["older_than"]=> string(3) "90d" ["name_regex"]=> NULL ["name_regex_keep"]=> NULL ["next_run_at"]=> string(24) "2020-09-29T07:15:02.945Z" } ["issues_enabled"]=> bool(true) ["merge_requests_enabled"]=> bool(true) ["wiki_enabled"]=> bool(true) ["jobs_enabled"]=> bool(true) ["snippets_enabled"]=> bool(true) ["service_desk_enabled"]=> bool(true) ["service_desk_address"]=> string(60) "incoming+llemeut-projet2-21256849-issue-@incoming.gitlab.com" ["can_create_merge_request_in"]=> bool(true) ["issues_access_level"]=> string(7) "enabled" ["repository_access_level"]=> string(7) "enabled" ["merge_requests_access_level"]=> string(7) "enabled" ["forking_access_level"]=> string(7) "enabled" ["wiki_access_level"]=> string(7) "enabled" ["builds_access_level"]=> string(7) "enabled" ["snippets_access_level"]=> string(7) "enabled" ["pages_access_level"]=> string(7) "private" ["emails_disabled"]=> NULL ["shared_runners_enabled"]=> bool(true) ["lfs_enabled"]=> bool(true) ["creator_id"]=> int(7126894) ["import_status"]=> string(4) "none" ["open_issues_count"]=> int(0) ["ci_default_git_depth"]=> int(50) ["public_jobs"]=> bool(true) ["build_timeout"]=> int(3600) ["auto_cancel_pending_pipelines"]=> string(7) "enabled" ["build_coverage_regex"]=> NULL ["ci_config_path"]=> string(0) "" ["shared_with_groups"]=> array(1) {
            [0]=> array(5) {
                ["group_id"]=> int(9661888) ["group_name"]=> string(7) "itescia" ["group_full_path"]=> string(7) "itescia" ["group_access_level"]=> int(40) ["expires_at"]=> NULL } } ["only_allow_merge_if_pipeline_succeeds"]=> bool(false) ["allow_merge_on_skipped_pipeline"]=> NULL ["request_access_enabled"]=> bool(true) ["only_allow_merge_if_all_discussions_are_resolved"]=> bool(false) ["remove_source_branch_after_merge"]=> bool(true) ["printing_merge_request_link_enabled"]=> bool(true) ["merge_method"]=> string(5) "merge" ["suggestion_commit_message"]=> NULL ["auto_devops_enabled"]=> bool(false) ["auto_devops_deploy_strategy"]=> string(10) "continuous" ["autoclose_referenced_issues"]=> bool(true) ["external_authorization_classification_label"]=> string(0) "" ["compliance_frameworks"]=> array(0) {
        } ["permissions"]=> array(2) {
            ["project_access"]=> array(2) {
                ["access_level"]=> int(40) ["notification_level"]=> int(3) } ["group_access"]=> NULL } } [6]=> array(70) {
        ["id"]=> int(21221266) ["description"]=> string(0) "" ["name"]=> string(7) "projet1" ["name_with_namespace"]=> string(22) "Loic Le Meut / projet1" ["path"]=> string(7) "projet1" ["path_with_namespace"]=> string(15) "llemeut/projet1" ["created_at"]=> string(24) "2020-09-18T16:13:52.241Z" ["default_branch"]=> string(6) "master" ["tag_list"]=> array(0) {
        } ["ssh_url_to_repo"]=> string(34) "git@gitlab.com:llemeut/projet1.git" ["http_url_to_repo"]=> string(38) "https://gitlab.com/llemeut/projet1.git" ["web_url"]=> string(34) "https://gitlab.com/llemeut/projet1" ["readme_url"]=> string(58) "https://gitlab.com/llemeut/projet1/-/blob/master/README.md" ["avatar_url"]=> NULL ["forks_count"]=> int(0) ["star_count"]=> int(0) ["last_activity_at"]=> string(24) "2020-10-07T07:51:03.874Z" ["namespace"]=> array(8) {
            ["id"]=> int(9415460) ["name"]=> string(12) "Loic Le Meut" ["path"]=> string(7) "llemeut" ["kind"]=> string(4) "user" ["full_path"]=> string(7) "llemeut" ["parent_id"]=> NULL ["avatar_url"]=> string(84) "https://secure.gravatar.com/avatar/60525e27078933b6086f324703846462?s=80&d=identicon" ["web_url"]=> string(26) "https://gitlab.com/llemeut" } ["_links"]=> array(7) {
            ["self"]=> string(43) "https://gitlab.com/api/v4/projects/21221266" ["issues"]=> string(50) "https://gitlab.com/api/v4/projects/21221266/issues" ["merge_requests"]=> string(58) "https://gitlab.com/api/v4/projects/21221266/merge_requests" ["repo_branches"]=> string(63) "https://gitlab.com/api/v4/projects/21221266/repository/branches" ["labels"]=> string(50) "https://gitlab.com/api/v4/projects/21221266/labels" ["events"]=> string(50) "https://gitlab.com/api/v4/projects/21221266/events" ["members"]=> string(51) "https://gitlab.com/api/v4/projects/21221266/members" } ["packages_enabled"]=> bool(true) ["empty_repo"]=> bool(false) ["archived"]=> bool(false) ["visibility"]=> string(7) "private" ["owner"]=> array(6) {
            ["id"]=> int(7126894) ["name"]=> string(12) "Loic Le Meut" ["username"]=> string(7) "llemeut" ["state"]=> string(6) "active" ["avatar_url"]=> string(84) "https://secure.gravatar.com/avatar/60525e27078933b6086f324703846462?s=80&d=identicon" ["web_url"]=> string(26) "https://gitlab.com/llemeut" } ["resolve_outdated_diff_discussions"]=> bool(false) ["container_registry_enabled"]=> bool(true) ["container_expiration_policy"]=> array(7) {
            ["cadence"]=> string(2) "1d" ["enabled"]=> bool(true) ["keep_n"]=> int(10) ["older_than"]=> string(3) "90d" ["name_regex"]=> NULL ["name_regex_keep"]=> NULL ["next_run_at"]=> string(24) "2020-09-29T07:03:17.260Z" } ["issues_enabled"]=> bool(true) ["merge_requests_enabled"]=> bool(true) ["wiki_enabled"]=> bool(true) ["jobs_enabled"]=> bool(true) ["snippets_enabled"]=> bool(true) ["service_desk_enabled"]=> bool(true) ["service_desk_address"]=> string(60) "incoming+llemeut-projet1-21221266-issue-@incoming.gitlab.com" ["can_create_merge_request_in"]=> bool(true) ["issues_access_level"]=> string(7) "enabled" ["repository_access_level"]=> string(7) "enabled" ["merge_requests_access_level"]=> string(7) "enabled" ["forking_access_level"]=> string(7) "enabled" ["wiki_access_level"]=> string(7) "enabled" ["builds_access_level"]=> string(7) "enabled" ["snippets_access_level"]=> string(7) "enabled" ["pages_access_level"]=> string(7) "private" ["emails_disabled"]=> NULL ["shared_runners_enabled"]=> bool(true) ["lfs_enabled"]=> bool(true) ["creator_id"]=> int(7126894) ["import_status"]=> string(4) "none" ["open_issues_count"]=> int(0) ["ci_default_git_depth"]=> int(50) ["public_jobs"]=> bool(true) ["build_timeout"]=> int(3600) ["auto_cancel_pending_pipelines"]=> string(7) "enabled" ["build_coverage_regex"]=> NULL ["ci_config_path"]=> string(0) "" ["shared_with_groups"]=> array(1) {
            [0]=> array(5) {
                ["group_id"]=> int(9661888) ["group_name"]=> string(7) "itescia" ["group_full_path"]=> string(7) "itescia" ["group_access_level"]=> int(40) ["expires_at"]=> NULL } } ["only_allow_merge_if_pipeline_succeeds"]=> bool(false) ["allow_merge_on_skipped_pipeline"]=> NULL ["request_access_enabled"]=> bool(true) ["only_allow_merge_if_all_discussions_are_resolved"]=> bool(false) ["remove_source_branch_after_merge"]=> bool(true) ["printing_merge_request_link_enabled"]=> bool(true) ["merge_method"]=> string(5) "merge" ["suggestion_commit_message"]=> NULL ["auto_devops_enabled"]=> bool(false) ["auto_devops_deploy_strategy"]=> string(10) "continuous" ["autoclose_referenced_issues"]=> bool(true) ["external_authorization_classification_label"]=> string(0) "" ["compliance_frameworks"]=> array(0) {
        } ["permissions"]=> array(2) {
            ["project_access"]=> array(2) {
                ["access_level"]=> int(40) ["notification_level"]=> int(3) } ["group_access"]=> NULL } } }